version: "3.9"
services:
  social-graph-service:
    image: andraderf/mysocial:basicot
    hostname: social-graph-service
    #    ports:
    #      - 10000:9090
    depends_on:
      jaeger-agent:
        condition: service_started
      otel-collector:
        condition: service_started
      social-graph-mongodb:
        condition: service_started
    restart: always
    entrypoint: SocialGraphService
    volumes:
      - ./config:/social-network-microservices/config
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=OT-social-graph-service

  social-graph-mongodb:
    image: mongo:4.4.6
    hostname: social-graph-mongodb
    # ports:
    #   - 27018:27017
    restart: always

  social-graph-redis:
    image: redis
    hostname: social-graph-redis
    # ports:
    #   - 6380:6379
    restart: always

  home-timeline-redis:
    image: redis
    hostname: home-timeline-redis
    # ports:
    #   - 6381:6379
    restart: always

  compose-post-service:
    image: andraderf/mysocial:basicot
    hostname: compose-post-service
    #    ports:
    #      - 10001:9090
    restart: always
    depends_on:
      jaeger-agent:
        condition: service_started
      otel-collector:
        condition: service_started
    entrypoint: ComposePostService
    volumes:
      - ./config:/social-network-microservices/config
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=OT-compose-post-service

  post-storage-service:
    image: andraderf/mysocial:basicot
    hostname: post-storage-service
    ports:
      - 10002:9090
    restart: always
    depends_on:
      jaeger-agent:
        condition: service_started
      otel-collector:
        condition: service_started
      post-storage-mongodb:
        condition: service_started
    entrypoint: PostStorageService
    volumes:
      - ./config:/social-network-microservices/config
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=OT-post-storage-service

  post-storage-memcached:
    image: memcached
    hostname: post-storage-memcached
    #    ports:
    #      - 11212:11211
    restart: always

  post-storage-mongodb:
    image: mongo:4.4.6
    hostname: post-storage-mongodb
    #    ports:
    #      - 27019:27017
    restart: always

  user-timeline-service:
    image: andraderf/mysocial:basicot
    hostname: user-timeline-service
    #    ports:
    #      - 10003:9090
    restart: always
    depends_on:
      jaeger-agent:
        condition: service_started
      otel-collector:
        condition: service_started
      user-timeline-mongodb:
        condition: service_started
    entrypoint: UserTimelineService
    volumes:
      - ./config:/social-network-microservices/config
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=OT-user-timeline-service


  user-timeline-redis:
    image: redis
    hostname: user-timeline-redis
    #    ports:
    #      - 6383:6379
    restart: always

  user-timeline-mongodb:
    image: mongo:4.4.6
    hostname: user-timeline-mongodb
    #    ports:
    #      - 27020:27017
    restart: always

  url-shorten-service:
    image: andraderf/mysocial:basicot
    hostname: url-shorten-service
    #    ports:
    #      - 10004:9090
    restart: always
    entrypoint: UrlShortenService
    depends_on:
      jaeger-agent:
        condition: service_started
      otel-collector:
        condition: service_started
      url-shorten-mongodb:
        condition: service_started
    volumes:
      - ./config:/social-network-microservices/config
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=OT-url-shorten-service


  url-shorten-memcached:
    image: memcached
    hostname: url-shorten-memcached
    #    ports:
    #      - 11213:11211
    restart: always

  url-shorten-mongodb:
    image: mongo:4.4.6
    hostname: url-shorten-mongodb
    #    ports:
    #      - 27021:27017
    restart: always

  user-service:
    image: andraderf/mysocial:basicot
    hostname: user-service
    #    ports:
    #      - 10005:9090
    restart: always
    depends_on:
      jaeger-agent:
        condition: service_started
      otel-collector:
        condition: service_started
      user-mongodb:
        condition: service_started
    entrypoint: UserService
    volumes:
      - ./config:/social-network-microservices/config
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=OT-user-service

  user-memcached:
    image: memcached
    hostname: user-memcached
    #    ports:
    #      - 11214:11211
    restart: always

  user-mongodb:
    image: mongo:4.4.6
    hostname: user-mongodb
    # ports:
    #   - 27023:27017
    restart: always

  media-service:
    image: andraderf/mysocial:basicot
    hostname: media-service
    #    ports:
    #      - 10006:9090
    depends_on:
      jaeger-agent:
        condition: service_started
      media-mongodb:
        condition: service_started
      otel-collector:
        condition: service_started
    restart: always
    entrypoint: MediaService
    volumes:
      - ./config:/social-network-microservices/config
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=OT-media-service


  media-memcached:
    image: memcached
    hostname: media-memcached
    #    ports:
    #      - 11215:11211
    restart: always

  media-mongodb:
    image: mongo:4.4.6
    hostname: media-mongodb
    #    ports:
    #      - 27024:27017
    restart: always

  text-service:
    image: andraderf/mysocial:basicot
    hostname: text-service
    #    ports:
    #      - 10007:9090
    restart: always
    depends_on:
      jaeger-agent:
        condition: service_started
      otel-collector:
        condition: service_started
    entrypoint: TextService
    volumes:
      - ./config:/social-network-microservices/config
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=OT-text-service


  unique-id-service:
    image: andraderf/mysocial:basicot
    hostname: unique-id-service
    #    ports:
    #      - 10008:9090
    restart: always
    depends_on:
      jaeger-agent:
        condition: service_started
      otel-collector:
        condition: service_started
    entrypoint: UniqueIdService
    volumes:
      - ./config:/social-network-microservices/config
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=OT-unique-id-service


  user-mention-service:
    image: andraderf/mysocial:basicot
    hostname: user-mention-service
    #    ports:
    #      - 10009:9090
    depends_on:
      jaeger-agent:
        condition: service_started
      otel-collector:
        condition: service_started
    restart: always
    entrypoint: UserMentionService
    volumes:
      - ./config:/social-network-microservices/config
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=OT-user-mention-service


  home-timeline-service:
    image: andraderf/mysocial:basicot
    hostname: home-timeline-service
    #    ports:
    #      - 10010:9090
    depends_on:
      jaeger-agent:
        condition: service_started
      otel-collector:
        condition: service_started

    restart: always
    entrypoint: HomeTimelineService
    volumes:
      - ./config:/social-network-microservices/config
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=OT-home-timeline-service


  nginx-thrift:
    image: andraderf/myxenial:updateresty
    hostname: nginx-thrift
    ports:
      - 8080:8080
    depends_on:
      jaeger-agent:
        condition: service_started
      otel-collector:
        condition: service_started
    restart: always
    volumes:
      - ./nginx-web-server/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      - ./nginx-web-server/pages:/usr/local/openresty/nginx/pages
      - ./nginx-web-server/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx-web-server/jaeger-config.json:/usr/local/openresty/nginx/jaeger-config.json
      - ./gen-lua:/gen-lua
      - ./docker/openresty-thrift/lua-thrift:/usr/local/openresty/lualib/thrift
      - ./nginx-web-server/conf/opentelemetry_module.conf:/usr/local/openresty/nginx/conf/opentelemetry_module.conf
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=OT-nginx-web-server

  media-frontend:
    image: yg397/media-frontend:xenial
    hostname: media-frontend
    ports:
      - 8081:8080
    restart: always
    depends_on:
      jaeger-agent:
        condition: service_started
      otel-collector:
        condition: service_started
    volumes:
      - ./media-frontend/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      - ./media-frontend/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf

  jaeger-agent:
    image: jaegertracing/all-in-one:latest
    volumes:
      - "./config/jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
    command: --query.ui-config /etc/jaeger/jaeger-ui.json
    ports:
      #      - 5775:5775/udp
      #      - 6831:6831/udp
      #      - 6832:6832/udp
      #      - 5778:5778
      - 16686:16686
      #      - 14268:14268
      #      - 9411:9411
      - 4318:4318
      - 4317:4317
    restart: always
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - "./config/otel-collector-config.yml:/etc/otelcol/otel-collector-config.yml"
    command: --config /etc/otelcol/otel-collector-config.yml
    depends_on:
      jaeger-agent:
        condition: service_started
  
  tracegen:
      image: jaegertracing/jaeger-tracegen:latest
      environment:
        - JAEGER_AGENT_HOST=otel-collector
        - JAEGER_AGENT_PORT=6831
      command: ["-duration", "10s", "-workers", "3", "-pause", "250ms"]
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"