receivers:
  otlp:
    protocols:
      grpc:
      http:
  jaeger:
    protocols:
      thrift_compact:

  # Dummy receiver that's never used, because a pipeline is required to have one.
  otlp/spanmetrics:
    protocols:
      grpc:
        endpoint: "localhost:65535"

extensions:
  health_check:
  pprof:
  zpages:
    endpoint: localhost:55679

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  jaeger:
    endpoint: "jaeger-agent:14250"
    tls:
      insecure: true
    
  otlp:
    endpoint: "jaeger-agent:14250"
    tls:
      insecure: true

  logging:
    verbosity: detailed

processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheus

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp,jaeger]
      processors: [spanmetrics, batch]
      exporters: [jaeger,logging]
    # The exporter name in this pipeline must match the spanmetrics.metrics_exporter name.
    # The receiver is just a dummy and never used; added to pass validation requiring at least one receiver in a pipeline.
    metrics/spanmetrics:
      receivers: [otlp/spanmetrics]
      exporters: [prometheus]
    metrics:
      receivers: [otlp/spanmetrics]
      # The metrics_exporter must be present in this list.
      exporters: [prometheus]