name: prometheus
component: obeservability
portLb:
  port: 9090
  targetPort: 9090

ports:
  - port: 9090
    targetPort: 9090

container:
  image: prom/prometheus
  imageVersion: v2.36.2
  name: prometheus

configMaps:
  - name: prometheus-exporter-loader.yaml
    mountPath: /etc/prometheus/prometheus.yml
    value: prometheus-exporter-loader

ClusterRole:
  rules:
    - apiGroups:
      - ''
      resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
      verbs: '"get", "list", "watch"'
    - apiGroups:
      - extensions
      resources:
      - ingress
      verbs: '"get", "list", "watch"'
  nonResourceURLs: "/metrics"
  verbs: "get"

clusterrolebinding:
  serviceaccount:
    name: 
    namespace: 
    